const MOVIES = {
  LOAD: "MOVIES_LOAD",
  LOAD_SUCCESS: "MOVIES_LOAD_SUCCESS",
  LOAD_FAIL: "MOVIES_LOAD_FAIL",
};

const INFINITE_MOVIES = {
  LOAD: "INFINITE_MOVIES_LOAD",
  LOAD_SUCCESS: "INFINITE_MOVIES_LOAD_SUCCESS",
  LOAD_FAIL: "INFINITE_MOVIES_LOAD_FAIL",
};

const MOVIE = {
  LOAD: "MOVIE_LOAD",
  LOAD_SUCCESS: "MOVIE_LOAD_SUCCESS",
  LOAD_FAIL: "MOVIE_LOAD_FAIL",
};

const SEARCH = {
  SHOW: "SEARCH_SHOW",
  HIDE: "SEARCH_HIDE",
};

const UPDATE = "UPDATE";
const REFRESH_PAGE = "REFRESH_PAGE";
const SAVE_ID = "SAVE_ID";
const ADD_FAVOURITE = "ADD_FAVOURITE";
const DELETE_FAVOURITE = "DELETE_FAVOURITE";
const STAR_TRUE = "STAR_TRUE";
const STAR_FALSE = "STAR_FALSE";
const LOCAL_STORAGE_GET = "LOCAL_STORAGE_GET";
const SET_FAVOURITES = "SET_FAVOURITES";

export {
  MOVIES,
  MOVIE,
  UPDATE,
  REFRESH_PAGE,
  SAVE_ID,
  ADD_FAVOURITE,
  DELETE_FAVOURITE,
  STAR_TRUE,
  STAR_FALSE,
  SEARCH,
  LOCAL_STORAGE_GET,
  SET_FAVOURITES,
  INFINITE_MOVIES,
};
